---

- hosts: all
  gather_facts: true
  roles:
    - docker
    - k8s-all

- hosts: kube-masters
  gather_facts: true
  roles:
    - k8s-master
    - kubectl-local

# this is limited in the role to only worker nodes, allows node to get master ip
- hosts: all
  gather_facts: true
  become: yes
  roles:
    - k8s-node

- hosts: kube-masters
  gather_facts: true
  roles:
    - ceph-admin
    - k8s-addons

