---

- name: Start kubeadm init
  debug: msg="Starting kubeadm init task"


- include: ../k8s-all/tasks/advertise-ip.yml

- name: Check if kubeadm was already run
  stat:
    path: "/var/lib/etcd"
  register:
    etcd_dir

- name: Template kubeadm-init.conf.tpl to /tmp/kubeadm-init.conf
  template:
    src: kubeadm-init.conf.tpl
    dest: /tmp/kubeadm-init.conf
    mode: 0640
  become: True

- name: Kubeadm init
  become: True
  command: "kubeadm init --config=/tmp/kubeadm-init.conf"
  register: kubeadm_init_out
  when: not etcd_dir.stat.exists

- name: Log Kubeadm init
  debug: msg="{{ kubeadm_init_out }}"
  when: kubeadm_init_out.changed

- name: Creates directory
  file: path=.kube state=directory

# Note ansible `copy` doesn't work here because of root privilege required for /etc
- name: Copy admin.conf to ~/.kube/config
  command: cp /etc/kubernetes/admin.conf /home/{{ username }}/.kube/config
  become: True

- name: Chown .kube/config
  become: True
  command: chown -R {{ username }}:{{ username }} /home/{{ username }}/.kube/
