---

- include: iptables.yml
- include: kubeadm-init.yml
- include: rbac.yml


# Networking overlay
- include: canal.yml
  when: network_driver == 'canal'
- include: weave.yml
  when: network_driver == 'weave'

# Package manager
- include: helm.yml
  when: helm_enabled

# Storage
- include: openstack-cinder.yml
  when:
    - dynamic_provision_enabled
    - dynamic_provisioner == 'openstack-cinder'

- include: ceph.yml
  when:
    - dynamic_provision_enabled
    - dynamic_provisioner == 'ceph'
