prefix="jascott1"
node-count="3"
internal-ip-pool="private-net-justinascott"
floating-ip-pool="public"
#ubuntu or centos
os="ubuntu"
image-flavor="m1.small"
security-groups="default"
key-pair="jascott1-jfc"
private-key-file="/Users/jascott1/.ssh/jascott1-jfc"
