---

- name: Get node array for ceph
  set_fact:
    node_ips: "{{ groups['kube-workers'] | map('extract', hostvars, ['ansible_ssh_host']) | list | join(' ') }}"

- name: ssh-keyscan ceph nodes
  shell:
    cmd: "ssh-keyscan -H {{ item }} >> ~/.ssh/known_hosts"
    chdir: ~/
  become: True
  become_user: ceph-deploy
  with_items: "{{ node_ips }}"

- name: ceph deploy install nodes
  shell:
    cmd: ceph-deploy --username ceph-deploy install {{ item }}
    chdir: ~/
  become: True
  become_user: ceph-deploy
  with_items: "{{ node_ips }}"

- name: ceph deploy admin nodes
  shell:
    cmd: ceph-deploy --username ceph-deploy admin {{ item }}
    chdir: ~/mycluster
  become: True
  become_user: ceph-deploy
  with_items: "{{ node_ips.split(' ') }}"

- name: ceph deploy install osd create
  shell:
    cmd: "ceph-deploy --username ceph-deploy osd create {{ item }}:vdb"
    chdir: ~/mycluster
  become: True
  become_user: ceph-deploy
  with_items: "{{ node_ips.split(' ') }}"

# TODO make dynamic based on node count
- name: ceph osd pool set kollavolumes pg_num 128
  shell:
    cmd: "ceph osd pool set kollavolumes pg_num 128"
  become: True

- name: ceph osd pool set kollavolumes pgp_num 128
  shell:
    cmd: "ceph osd pool set kollavolumes pgp_num 128"
  become: True


