---

- name: Start hostname
  debug: msg="Starting hostname task"

- include: tasks/advertise-ip.yml

- name: Add hostname to /etc/hosts
  replace:
    dest: /etc/hosts
    regexp: 'localhost'
    replace: 'localhost {{ inventory_hostname }}'
  become: True

- name: echo hostname
  shell: echo $(hostname -s)
  register: hostname

- name: echo IP
  shell: "ip address show dev ens3 scope global | awk '/inet / {split($2,var,\"/\"); print var[1]}'"
  register: ipaddress

- name: Add node hostname to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "{{ ipaddress.stdout }} {{ hostname.stdout }}"
  become: True

#- name: Add master hostname to /etc/hosts
#  lineinfile:
#    path: /etc/hosts
#    line: "{{ api_advertise_ip }} {{ hostname.stdout }}"
#  become: True
