---

- include: python.yml

- include: disable-security.yml

- include: hostname.yml

- include: k8s-deps.yml

- include: k8s-config.yml

- include: ceph-user.yml
  when:
      - dynamic_provision_enabled
      - dynamic_provisioner == 'ceph'

